name: Deploy to Server

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'

            - name: Install dependencies
              run: npm install

            - name: Build the app
              run: npm run build

    deploy:
        runs-on: ubuntu-20.04
        needs: build

        steps:
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2
              with:
                  command: 'cd /timewise-connect-backend && npm install && npm run build && pm2 restart your_app_entry_file.js'
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  host: ${{ secrets.SERVER_IP }}
