name: Deploy to Server

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'

            - name: Install dependencies
              run: npm install

            - name: Build the app
              run: npm run build

    deploy:
        runs-on: ubuntu-20.04
        needs: build

        steps:
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  REMOTE_HOST: ${{ secrets.SERVER_IP }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: '/www'
                  EXCLUDE: '/dist/, /node_modules/'
